// This file is automatically generated from your CSS. Any edits will be overwritten.
export const revealed: string;
export const mine: string;
export const win: string;
export const winKeyFrames: string;
