// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const button: string;
export const flag: string;
export const active: string;
export const wiggleKeyFrames: string;
