// This file is automatically generated from your CSS. Any edits will be overwritten.
export const standardDescription: string;
export const plusDescription: string;
export const plusPlusDescription: string;
